future: true
permalink: /blog/:title/
markdown: kramdown

exclude: [
    ".rvmrc",
    ".rbenv-version",
    "README.md",
    "Rakefile",
    "changelog.md",
    "node_modules",
    "gulpfile.js",
    ".editorconfig",
    "assets/components/*"
]

title : "SKGTech - Thessaloniki's Tech Community"
email: hello@skgtech.io
description: "A vibrant community of developers, designers, product people and entrepreneurs who live in Thessaloniki."
author :
  name : "SKGTech Contributors"
  email : "skg-developers@googlegroups.com"
  github : "skgtech"
  twitter : SKG_Tech
  # feedburner : feedname
githubrepo: "https://github.com/skgtech/skgtech.github.io"

production_url : https://skgtech.io

sass:
    sass_dir: ./_scss

# Open Graph data
og:
  app_id: "698696243515776"
  title: "Thessaloniki tech Community"
  site_name: "SKGTech"
  image: "https://skgtech.io/assets/img/skgtech-social-logo.png"

# Google Analytics
analytics :
  provider : google
  google :
    tracking_id : 'UA-41787746-3'
    domain: 'skgtech.io'

authors:
  thanpolas:
    name: Thanasis Polychronakis
    display_name: Thanasis
    gravatar: cbb9cafe03e785d80a9aa973c5e43c44
    email: thanpolas@gmail.com
    web: http://thanpol.as
    twitter: thanpolas
    github: thanpolas
  marga:
    name: Konstantinos Margaritis
    display_name: Konstantinos Margaritis
    gravatar: 15a64213080e0ee13d02f0eab0f8819b
    email: kostas@devitconf.org
    web: http://typeofundefined.io/
    twitter: _margaritis
    github: margaritis
